name: "Infection PHP"
description: "Run Infection PHP"

inputs:
  command:
    required: true
    description: "Infection command"

  cache-path:
    required: true
    description: "Infection cache path"

  stryker-token:
    required: false
    description: "Stryker token for submitting code coverage"

runs:
  using: "composite"

  steps:
    - name: "Create cache key"
      uses: "actions/github-script@v6"
      id: "cache-key"
      with:
        script: "return `ori-php-infection--job-${{ github.job }}--os-${{ runner.os }}--matrix-${{ toJson(matrix) }}--run`.replaceAll(',', '+').replaceAll(' ', '').replaceAll(/(?:\\r\\n|\\r|\\n)/g, '');"
        result-encoding: "string"

    - name: "Cache Infection data"
      uses: "actions/cache@v3"
      with:
        path: "${{ inputs.cache-path }}"
        key: "${{ steps.cache-key.outputs.result }}-${{ github.run_id }}"
        restore-keys: "${{ steps.cache-key.outputs.result }}-"

    - name: "Mutation tests with report"
      if: "${{ inputs.stryker-token }}"
      env:
        STRYKER_DASHBOARD_API_KEY: "${{ inputs.stryker-token }}"
      shell: "bash"
      run: "${{ inputs.command }}"

    - name: "Mutation tests"
      if: "${{ !inputs.stryker-token }}"
      shell: "bash"
      run: "${{ inputs.command }}"
