name: "PHPUnit"
description: "Run PHPUnit"

inputs:
  command:
    required: true
    description: "PHPUnit command"

  cache-path:
    required: true
    description: "PHPUnit cache path"

runs:
  using: "composite"

  steps:
    - name: "Create cache key"
      uses: "actions/github-script@v6"
      id: "cache-key"
      with:
        script: "return `ori-php-phpunit--job-${{ github.job }}--os-${{ runner.os }}--matrix-${{ toJson(matrix) }}--run`.replaceAll(',', '+').replaceAll(' ', '').replaceAll(/(?:\\r\\n|\\r|\\n)/g, '');"
        result-encoding: "string"

    - name: "Cache PHPUnit data"
      uses: "actions/cache@v3"
      with:
        path: "${{ inputs.cache-path }}"
        key: "${{ steps.cache-key.outputs.result }}-${{ github.run_id }}"
        restore-keys: "${{ steps.cache-key.outputs.result }}-"

    - name: "Setup problem matchers for PHPUnit"
      shell: "bash"
      run: 'echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"'

    - name: "Tests"
      shell: "bash"
      run: "${{ inputs.command }}"
