name: "PHPStan"
description: "Run PHPStan"

inputs:
  command:
    required: true
    description: "PHPStan command"

  cache-path:
    required: true
    description: "PHPStan cache path"

runs:
  using: "composite"

  steps:
    - name: "Create cache key"
      uses: "actions/github-script@v6"
      id: "cache-key"
      with:
        script: "return `ori-php-phpstan--job-${{ github.job }}--os-${{ runner.os }}--matrix-${{ toJson(matrix) }}--run`.replaceAll(',', '+').replaceAll(' ', '').replaceAll(/(?:\\r\\n|\\r|\\n)/g, '');"
        result-encoding: "string"

    - name: "Cache PHPStan data"
      uses: "actions/cache@v3"
      with:
        path: "${{ inputs.cache-path }}"
        key: "${{ steps.cache-key.outputs.result }}-${{ github.run_id }}"
        restore-keys: "${{ steps.cache-key.outputs.result }}-"

    - name: "PHPStan"
      shell: "bash"
      run: "${{ inputs.command }}"
