name: "Lock inactive closed issues and PRs"

on:
  workflow_call:
    inputs:
      issue-lock-inactive-days:
        required: false
        type: "string"
        default: "30"
        description: "Lock inactive closed issue after X days"

      pr-lock-inactive-days:
        required: false
        type: "string"
        default: "60"
        description: "Lock inactive closed PR after X days"

jobs:
  lock:
    name: "Lock"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Lock"
        uses: "dessant/lock-threads@v4"
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

          issue-inactive-days: "${{ inputs.issue-lock-inactive-days }}"
          issue-lock-reason: "resolved"
          issue-comment: >
            This issue has been automatically locked since there
            has not been any recent activity after it was closed.
            Please open a new issue for related bugs.

          pr-inactive-days: "${{ inputs.pr-lock-inactive-days }}"
          pr-lock-reason: "resolved"
          pr-comment: >
            This pull request has been automatically locked since there
            has not been any recent activity after it was closed.
            Please open a new issue for related bugs.
